data:
  genre_filter: genre_Comedy
  label_column: label
  raw_data:
    movies: movie_raw_data/movies.csv
    ratings: movie_raw_data/ratings.csv
  test_data_path: data/test.csv
  train_data_path: data/train.csv
  valid_data_path: data/valid.csv
experiment:
  name: comedy_only
model:
  architecture: deep_only
  dropout_rate: 0.0
  embedding_dim: 64
  hidden_units:
  - 256
  - 256
  - 256
train:
  batch_size: 1024
  epochs: 3
  learning_rate: 0.01
  momentum: 0.9
  optimizer: sgd
